.TH FINESSING_FINANCE 1 "Version 1.0.0" "Date: 2024/7/25"
.SH NAME
finessing_finance \- A finance program for managing personal finances

.SH SYNOPSIS
finessing_finance [OPTIONS]

.SH DESCRIPTION
finessing_finance is a command-line program designed to help users manage their personal finances. It provides various features for tracking income, expenses, and investing in the stock market.

.SH OPTIONS
The following options are supported:

.TP
.B \-h, \-\-help
Display the help message and exit.

.TP
.B \-\-version
Display the version of the program.

.SH AUTHOR
Written by Badger Code.

.SH NOTES
This program is provided AS IS with NO WARRANTY OF ANY KIND, INCLUDING THE WARRANTY OF DESIGN, MERCHANTABILITY, AND FITNESS FOR A PARTICULAR PURPOSE.

.SH HISTORY
Version 1.0.0: Initial release.